class FixColumnNamesInsurances < ActiveRecord::Migration[5.2]
  def change
    rename_column :insurances, :experience_with_export_country, :experience_with_importer_country
    rename_column :insurances, :agreed_payments_output, :agreed_payments_output_payment_term_short
    rename_column :insurances, :agreed_payments_time, :agreed_payments_time_payment_term_short
    rename_column :insurances, :agreed_payments_some_output, :agreed_payments_some_output_payment_term_short
    rename_column :insurances, :payment_vehichle, :payment_vehichle_payment_term_short
    
    rename_column :insurances, :number_of_installments, :number_of_installments_payment_term_short
    rename_column :insurances, :sonstige_kurzfrist_advance_payment_currency, :advance_payment_currency_payment_term_both
    rename_column :insurances, :sonstige_kurzfrist_advance_payment_amount, :advance_payment_amount_payment_term_both
    rename_column :insurances, :sonstige_kurzfrist_advance_payment_explain, :advance_payment_description_payment_term_both
    rename_column :insurances, :sonstige_kurzfrist_deposit_received, :deposit_received_payment_term_both
    rename_column :insurances, :sonstige_kurzfrist_repayment_structure, :repayment_structure_payment_term_both
    rename_column :insurances, :sonstige_kurzfrist_credit_start, :credit_start_date_payment_term_both
    rename_column :insurances, :sonstige_kurzfrist_credit_start_sonstige_explain, :credit_start_special_description_payment_term_both
    rename_column :insurances, :sonstige_kurzfrist_number_of_installments, :number_of_installments_payment_term_both
    rename_column :insurances, :sonstige_kurzfrist_payment_vehichle_explain, :payment_vehichle_explain_payment_term_both
    rename_column :insurances, :part_of_goods__sonstige_kurzfrist_certificate_of_origin, :has_german_certificate_of_origin_for_only_parts_of_good
    rename_column :insurances, :agreed_payments_currency, :agreed_payments_currency_payment_term_short
    rename_column :insurances, :agreed_payments_amount, :agreed_payments_amount_payment_term_short
    rename_column :insurances, :yes_export_requires_exportlicense, :is_export_licence_needed
    rename_column :insurances, :which_regulations_arises_exportlicense_requirement, :which_regulations_enforcing_exportlicense_requirement
    rename_column :insurances, :exportlicense_status, :export_license_status
    rename_column :insurances, :yes_deliver_secondhand_goods, :does_deliver_secondhand_goods
    rename_column :insurances, :yes_contract_already_signed_all_parties, :is_contract_already_signed_between_parties
    rename_column :insurances, :trade_contract_signing_date, :contract_signing_date
    rename_column :insurances, :yes_special_contract_structure, :has_special_contract_structure
    rename_column :insurances, :more_components_open_to_exporter_currency, :other_billed_items_in_contract_currency
    rename_column :insurances, :more_components_open_to_exporter_amount, :other_billed_items_in_contract_amount
    rename_column :insurances, :more_components_open_to_exporter_explain, :describe_other_billed_items_in_contract
    rename_column :insurances, :yes_charge_interest_to_importer, :is_interest_charged_to_importer
    rename_column :insurances, :yes_price_adjustment_clause_with_importer, :is_price_adjustment_clause_with_importer
    rename_column :insurances, :yes_goods_sent_multiple_deliveries, :is_good_sent_in_multiple_deliveries
    rename_column :insurances, :downpayment_delivery_currency, :downpayment_delivery_currency_payment_term_short
    rename_column :insurances, :downpayment_delivery_amount, :downpayment_delivery_amount_payment_term_short
    rename_column :insurances, :downpayment_delivery_description, :downpayment_delivery_description_payment_term_short
    rename_column :insurances, :explain_why_importer_buying_goods, :explain_why_importer_buying_good
    rename_column :insurances, :yes_deliver_part_of_overall_project_other_companies, :is_delivered_part_of_consortium_with_other_companies
    rename_column :insurances, :proportion_contract_security_provided, :proportion_of_good_covered_by_security
    rename_column :insurances, :importer_delivery_address_company_name, :importer_shipment_company_name
    rename_column :insurances, :importer_delivery_address_street, :importer_shipment_street
    rename_column :insurances, :importer_delivery_address_plz, :importer_shipment_plz
    rename_column :insurances, :importer_delivery_address_city, :importer_shipment_city
    rename_column :insurances, :importer_delivery_address_country, :importer_shipment_country
    rename_column :insurances, :trading_since_when_without_hermes_insurance, :years_trading_without_hermes_insurance
    rename_column :insurances, :exporter_company_dnnr, :exporter_dn_no
    rename_column :insurances, :exporter_company_plz, :exporter_plz
    rename_column :insurances, :exporter_company_city, :exporter_city
    rename_column :insurances, :exporter_company_country, :exporter_country
    rename_column :insurances, :exporter_company_representative_firstname, :exporter_representative_firstname
    rename_column :insurances, :exporter_company_representative_lastname, :exporter_representative_lastname
    rename_column :insurances, :exporter_company_representative_email, :exporter_representative_email
    rename_column :insurances, :exporter_company_representative_function, :exporter_representative_function
    rename_column :insurances, :exporter_company_representative_department, :exporte_representative_department
    rename_column :insurances, :exporter_company_name, :exporter_name
    rename_column :insurances, :explain_corruption_declaration_applies, :explain_corruption_sanctions
    rename_column :insurances, :information_inputted_best_of_knowledge, :is_all_information_provided_with_best_of_knowledge
    rename_column :insurances, :exporter_company_street, :exporter_street
    rename_column :insurances, :yes_residualriskapetite_minimum_five, :accept_partial_refinancing
    rename_column :insurances, :yes_investment_good, :is_investment_good
    rename_column :insurances, :yes_exporter_offers_servicing_for_goods, :is_servicing_for_goods_offered
    rename_column :insurances, :yes_sonstige_kurzfrist_certificate_of_origin, :has_german_certificate_of_origin
    rename_column :insurances, :yes_security_businnes_provided, :is_security_present_for_transaction
    rename_column :insurances, :yes_delivered_at_this_address, :is_shipment_address
    rename_column :insurances, :yes_exporter_influence_on_importer_management, :has_significant_influence_on_importer_management
    rename_column :insurances, :yes_previous_payment_experience_with_importer, :has_payment_experience_with_importer
    rename_column :insurances, :yes_previously_hermes_insurance_used, :has_previously_used_hermes_cover
    rename_column :insurances, :corruption_declaration_applies, :does_corruption_declaration_appy
    rename_column :insurances, :yes_payment_term_already_agreed, :has_agreed_payment_term_already
    rename_column :insurances, :accept_terms_conditions, :has_accepted_terms_conditions
    rename_column :insurances, :read_privacy_policy, :has_read_privacy_policy
    rename_column :insurances, :read_all_instructions, :has_read_all_instructions
    rename_column :insurances, :payment_term_shortterm, :payment_term_short
    rename_column :insurances, :payment_term_middleterm, :payment_term_mid
  end
end
