class RemoveFieldsFromInsurances < ActiveRecord::Migration[5.2]
  def change
      remove_column :insurances, :agreed_payments_amount2
      remove_column :insurances, :agreed_payments_output2
      remove_column :insurances, :agreed_payments_time2
      remove_column :insurances, :agreed_payments_some_output2
      remove_column :insurances, :agreed_payments_currency3
      remove_column :insurances, :agreed_payments_amount3
      remove_column :insurances, :agreed_payments_output3
      remove_column :insurances, :agreed_payments_time3
      remove_column :insurances, :agreed_payments_some_output3
      remove_column :insurances, :agreed_payments_currency4
      remove_column :insurances, :agreed_payments_amount4
      remove_column :insurances, :agreed_payments_output4
      remove_column :insurances, :agreed_payments_time4
      remove_column :insurances, :agreed_payments_some_output4
      remove_column :insurances, :agreed_payments_currency5
      remove_column :insurances, :agreed_payments_amount5
      remove_column :insurances, :agreed_payments_output5
      remove_column :insurances, :agreed_payments_time5
      remove_column :insurances, :agreed_payments_some_output5
      remove_column :insurances, :agreed_payments_currency6
      remove_column :insurances, :agreed_payments_amount6
      remove_column :insurances, :agreed_payments_output6
      remove_column :insurances, :agreed_payments_time6
      remove_column :insurances, :agreed_payments_some_output6
      remove_column :insurances, :agreed_payments_currency7
      remove_column :insurances, :agreed_payments_amount7
      remove_column :insurances, :agreed_payments_output7
      remove_column :insurances, :agreed_payments_time7
      remove_column :insurances, :agreed_payments_some_output7
      remove_column :insurances, :agreed_payments_currency8
      remove_column :insurances, :agreed_payments_amount8
      remove_column :insurances, :agreed_payments_output8
      remove_column :insurances, :agreed_payments_time8
      remove_column :insurances, :agreed_payments_some_output8
      remove_column :insurances, :agreed_payments_currency9
      remove_column :insurances, :agreed_payments_amount9
      remove_column :insurances, :agreed_payments_output9
      remove_column :insurances, :agreed_payments_time9
      remove_column :insurances, :agreed_payments_some_output9
      remove_column :insurances, :agreed_payments_currency10
      remove_column :insurances, :agreed_payments_amount10
      remove_column :insurances, :agreed_payments_output10
      remove_column :insurances, :agreed_payments_time10
      remove_column :insurances, :agreed_payments_some_output10
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_currency1
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_amount1
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_percent1
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_date1
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_output1
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_currency2
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_amount2
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_percent2
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_date2
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_output2
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_currency3
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_amount3
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_percent3
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_date3
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_output3
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_currency4
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_amount4
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_percent4
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_date4
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_output4
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_currency5
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_amount5
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_percent5
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_date5
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_output5
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_currency6
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_amount6
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_percent6
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_date6
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_output6
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_currency7
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_amount7
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_percent7
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_date7
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_output7
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_currency8
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_amount8
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_percent8
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_date8
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_output8
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_currency9
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_amount9
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_percent9
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_date9
      remove_column :insurances, :sonstige_kurzfrist_agreed_payment_output9
  end
end